import { envSettings } from "./env/envSettings";

// The service worker (generated by vite-plugin-pwa, see vite.config.js)
// precaches the app so that it starts offline, but it answers navigations from
// the network. Whether a reload brings the freshly deployed app therefore does
// not depend on which worker is in charge: as long as the server can be
// reached, the reload gets the new index.html and with it the new chunks.
//
// Swapping in the new worker before reloading is still worth doing, because
// only the worker controlling the page serves chunks from its precache - which
// is what keeps the new version working once the connection drops. It is an
// optimisation though, never a precondition: whatever becomes of it, we reload.

// `vite dev` does not emit a worker, so there is nothing to register there.
const registration: Promise<ServiceWorkerRegistration | undefined> =
  "serviceWorker" in navigator && !envSettings.isDev
    ? navigator.serviceWorker.register("/sw.js").catch((error: unknown) => {
        console.warn("Service worker registration failed.", error);
        return undefined;
      })
    : Promise.resolve(undefined);

// Installing a worker means downloading its whole precache, which takes a while
// on a slow connection. Past this we stop holding the reload back for it; the
// worker finishes in the background and takes over on the next app start.
const workerSwapTimeoutMs = 20_000;

/**
 * Updates the app to the deployed version by reloading it, after giving the
 * newest service worker the chance to take over first.
 */
export async function applyNewVersion(): Promise<void> {
  await Promise.race([
    activateNewestWorker().catch((error: unknown) => {
      console.warn("Could not activate the new service worker.", error);
    }),
    new Promise((resolve) => window.setTimeout(resolve, workerSwapTimeoutMs)),
  ]);

  location.reload();
}

async function activateNewestWorker(): Promise<void> {
  const swRegistration = await registration;
  if (!swRegistration) {
    return;
  }

  // Look for a newer worker even when one is already waiting: with two deploys
  // since this page loaded, the waiting one is behind as well.
  await swRegistration.update();

  // update() resolves once the worker it found has been created, which is well
  // before that worker has finished installing. Whether it then made it to
  // "installed" or failed and went "redundant" shows in registration.waiting.
  if (swRegistration.installing) {
    await waitForState(
      swRegistration.installing,
      (state) => state !== "installing",
    );
  }

  const waiting = swRegistration.waiting;
  if (!waiting) {
    return;
  }

  // The worker is generated in "prompt" mode: it stays in waiting until it gets
  // this message, see the listener in the generated sw.js.
  waiting.postMessage({ type: "SKIP_WAITING" });

  await waitForState(
    waiting,
    (state) => state === "activated" || state === "redundant",
  );
}

function waitForState(
  worker: ServiceWorker,
  isReached: (state: ServiceWorkerState) => boolean,
): Promise<void> {
  return new Promise((resolve) => {
    function checkState() {
      if (!isReached(worker.state)) {
        return;
      }

      worker.removeEventListener("statechange", checkState);
      resolve();
    }

    worker.addEventListener("statechange", checkState);

    // The worker can have moved on before we subscribed, in which case no
    // further statechange is coming.
    checkState();
  });
}
