import { envSettings } from "../env/envSettings";
import OneSignal from "react-onesignal";

export const setUpOneSignal = (oneSignalUserId: string) => {
  OneSignal.init({
    appId: envSettings.notifications.appId,
    allowLocalhostAsSecureOrigin: envSettings.isDev,
    notificationClickHandlerAction: "focus",
    notificationClickHandlerMatch: "exact",
    // Use the unified PWA service worker (generated by vite-plugin-pwa) instead
    // of registering a second OneSignal-only worker. That worker importScripts
    // the OneSignal SDK worker, so push works from the same SW that handles
    // offline caching, and there's no scope-"/" collision. Note: the PWA worker
    // is not emitted by `vite dev`, so OneSignal push only initialises in a
    // production build / preview.
    serviceWorkerPath: "sw.js",
    serviceWorkerParam: { scope: "/" },
  }).then(() => {
    OneSignal.login(oneSignalUserId)
      .then(() => {
        console.log("OneSignal login successful.");
      })
      .catch((e) => {
        console.error("OneSignal login error:", e);
      });

    OneSignal.Notifications.addEventListener("click", (e) => {
      alert(`Notification button "${e.result?.actionId}" was clicked.`);
    });
  });
};

export const optInPushNotifications = () => {
  if (OneSignal.User.PushSubscription.optedIn) {
    return;
  }

  OneSignal.User.PushSubscription.optIn();
};
