name: Api

on:
  push:
    paths-ignore:
      - "api/**"
      - ".github/workflows/api.yml"

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No checks required"'
