name: Api

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
  workflow_dispatch:
    inputs:
      deploy:
        description: "Force deployment"
        required: false
        default: "false"

jobs:
  build:
    name: Build API
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x.x"

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./api

      - name: Start MongoDB (for tests)
        run: |
          Set-Service mongodb -StartupType Automatic
          Start-Service -Name mongodb

      - name: Run tests
        run: dotnet test
        working-directory: ./api

      - name: Get current time
        id: current-time
        uses: gerred/actions/current-time@master

      - name: Publish
        run: dotnet publish ./Engraved.Api/Engraved.Api.csproj -c Release -o "${{env.DOTNET_ROOT}}\Engraved.Api" -p:SourceRevisionId=${{github.run_number}}+${{github.sha}}+${{steps.current-time.outputs.time}}
        working-directory: ./api

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ${{env.DOTNET_ROOT}}\Engraved.Api

  deploy-windows:
    name: Deploy API (Linux)
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event.inputs.deploy == 'true'

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api

      - name: Deploy to Azure App Service (Windows)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "engraved"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CF17B8AFBCD14051B9CD5C069F5E294E }}
          package: .

  deploy-linux:
    name: Deploy API (Windows)
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event.inputs.deploy == 'true'

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api

      - name: Deploy to Azure App Service (Linux)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "engraved-lnx"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CF17B8AFBCD14051B9CD5C069F5E294E_LNX }}
          package: .
