name: Api

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
  workflow_dispatch:
    inputs:
      deploy:
        description: "Force deployment"
        required: false
        default: "false"

jobs:
  build:
    name: Build API
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
          include-prerelease: false

      - name: Build
        run: dotnet build --configuration Release -p:SourceRevisionId=${{github.sha}}+${{github.run_number]}
        working-directory: ./api

      - name: Start MongoDB (for tests)
        run: |
          Set-Service mongodb -StartupType Automatic
          Start-Service -Name mongodb

      - name: Run tests
        run: dotnet test
        working-directory: ./api

      - name: Publish
        run: dotnet publish ./Metrix.Api/Metrix.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/Metrix.Api
        working-directory: ./api

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ${{env.DOTNET_ROOT}}/Metrix.Api

  deploy:
    name: Deploy API
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event.inputs.deploy == 'true'

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api

      - name: Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "metrix-api"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C73DA976C93E4096B745D8FA1460090E }}
          package: .
