name: App

on:
  push:
    paths-ignore:
      - "app/**"
      - ".github/workflows/app.yml"

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No checks required"'
