name: Playwright Tests
on:
  push:
    paths:
      - "*"
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.x.x"
    
    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm ci
      working-directory: ./tests
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./tests
    
    - name: Boot servers and run tests
      run: npm run ci:run
      working-directory: ./tests

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
